name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          
          plugin_achievements: yes
          plugin_achievements_threshold: C        # Display achievements with rank B or higher
          plugin_achievements_secrets: yes        # Display unlocked secrets achievements
          plugin_achievements_limit: 0            # Display all unlocked achievement matching threshold and secrets params
          plugin_achievements_display: detailed   # Use compact display
