name: Github Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 10 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps: 
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # settings
          user: Awilum
          template: classic
          filename: github-metrics.json
          config_output: json
          config_timezone: Europe/Moscow
          base: header, activity, community, repositories, metadata
          commits_authoring: Awilum, hello@romanenko.digital, sergey.romanenko@flextype.org, 477114+awilum@users.noreply.github.com, support@flextype.org, awilum@msn.com, awilum@yandex.ru
          
          # plugin: lines
          plugin_lines: yes
          
          # plugin: languages
          plugin_languages: yes
          plugin_languages_categories: markup, programming, data, prose
          plugin_languages_colors: github
          plugin_languages_limit: 0
          plugin_languages_recent_categories: markup, programming, data, prose
          plugin_languages_recent_days: 0
          plugin_languages_recent_load: 1000
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_languages_ignored: hack
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 0
          plugin_activity_filter: issue, pr, release, push, commit

