name: Github Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 10 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps: 
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # settings
          template: classic
          filename: github-metrics.json
          config_output: json
        
          # plugin: lines
          plugin_lines: yes
          
          # plugin: languages
          plugin_languages: yes
          plugin_languages_limit: 30
          
      

